### ISSUE TITLE
Citation entry for every subject

### ISSUE THREAD

**Issue by mattpetrucci** [keenon/AddBiomechanics#197]
With the new updates on the dev server, the desired citation is at the subject level, where we probably want this at the folder/dataset level (so the user only has to enter it once per study, vs. per each subject).

**Comment by mattpetrucci** [comment]
On a related note, do we want to add to the tips and tricks that we suggest organizing data into folders for studies? Currently people might just create subjects without organizing them into folders.

**Comment by AlbertoCasasOrtiz** [comment]
In the new PR https://github.com/keenon/AddBiomechanics/pull/206, I have reintegrated the desired citation (and the rest of the fields) into the dataset folders, but I have not removed it from subjects since it goes in a different file.

I agree with suggesting in tips and tricks (and maybe in FAQ too) to organize everything in folders.
