### ISSUE TITLE
Increased cost in addbiomechanics AWS account

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [keenon/AddBiomechanics#265]
From slack conversation:

> Confirmed it is just addbiomechanics, and not other apps.
>
> Increased from $200 to $2000 in the last two months.
> 
> Probably due to high number of downloads, since uploads are low cost (We should take a look at the command line API, since people can use it to download data).

**Comment by AlbertoCasasOrtiz** [comment]
News:

Every months there is a refund that adjusts the price and It happened last month as well. We think the price shown is a projection and it is adjusted at the end of the month with the refund.

**Comment by nickbianco** [comment]
@keenon recently fixed a bug related to the data harvesters that likely was the issue in the cost increases: https://github.com/keenon/AddBiomechanics/pull/268.

Essentially, the data harvester was trying to copy the same subject repeatedly due to a seg fault, resulting in many unnecessary downloads. We should probably keep the issue open either way to make sure this PR actually fixes the cost increase (unless there's a way to check download costs in real-time?)

**Comment by mattpetrucci** [comment]
Sounds good. We can technically break down the cost by whatever data range makes sense (down to a day, or last 7 days, etc.)

Maybe good to keep it open and recheck in a week or so?

**Comment by nickbianco** [comment]
Sounds good!

**Comment by AlbertoCasasOrtiz** [comment]
Hi, it is been 10 days since last comment. Should we close this issue?

**Comment by mattpetrucci** [comment]
I think we can close. We confirmed the numbers
