### ISSUE TITLE
Add basic support info 

### ISSUE THREAD

**Issue by jenhicks** [keenon/AddBiomechanics#41]
Within the app, there is no link to documentation, tips and tricks, a forum etc. 

To get started, we could flesh out this page a little more:
https://addbiomechanics.org/instructions.html

- [x] Point to the user forum
- [x] Check-in with Keenon on monitoring the forum (and add additional moderators)
- [x] Point to pre-print, tutorials, webinars, and other materials as they become available. 
- [x] Make sure current content is up-to-date

Longer term, perhaps move to wiki-based documentation.

**Comment by AlbertoCasasOrtiz** [comment]
Related to this issue, I have added links to Help, Terms of Service and Forums in addBiomechanics app. I have marked not marked anything as completed since this is not in dev or prod yet.

I like the idea of moving to wiki-based documentation. Seems like Keenon already started it some time ago: https://github.com/keenon/AddBiomechanics/wiki

**Comment by jenhicks** [comment]
The pointers to help in the app are great! I am going to close this one and we can add more specific updates as separate issues (there are a couple issues like this already)
