### ISSUE TITLE
Add a page explaining our data sharing model and include example consent language 

### ISSUE THREAD

**Issue by jenhicks** [keenon/AddBiomechanics#99]
@keenon @nickbianco @mattpetrucci

I started a draft here: 
https://docs.google.com/document/d/1T8GX0jySJ-Z6pTIw1txgUrzsH-JK8mRkMtw2SRJRJwE/edit

Nick, tagging you since this relates to the other issue about how the draft/publish mechanism works. 

@keenon can we also add Matt to the project so it is easier to tag him? (I don't think I have permissions to do this).

**Comment by jenhicks** [comment]
@frabjous5

**Comment by jenhicks** [comment]
@nickbianco @keenon 

With the paper getting close, should we try to finalize this page? A few questions to resolve:

(1) License for AddBiomechanics
(2) Do we want to automatically publish draft data after some holding period?
(3) Do we want to automatically flag and contact people or take any other action for folks who have too much data in the private folder?

Featuring people who share lots of data (and other "carrots") will be great in the future, but I think OK to hold on for now. 

Doc is here again for reference:
https://docs.google.com/document/d/1T8GX0jySJ-Z6pTIw1txgUrzsH-JK8mRkMtw2SRJRJwE/edit

**Comment by nickbianco** [comment]
(1) The Apache 2.0 license would seem to make sense to sync with OpenSim's license, but I'll let @keenon leave his thoughts on this.

(2) The "publish after 6 months" approach seems to be a reasonable compromise. As long as we make it clear that any data put into a Draft folder could eventually be made public.

(3) I'm still unsure about the best way to handle the Private folder, but my instinct is to be a little more restrictive. Even if we eventually flag users about too much data in these folders, I wonder if people will still default to using Private even when they don't need to. Would it make sense at all to only open a Private folder if users can show that data is not shareable and have a time limit on the folder? This might not be the right solution, but it would be good to find a way to push users towards Draft/Publish mechanism first.

**Comment by nickbianco** [comment]
Scratch that: I'll move it to "Done" and we can discusss at the next sprint planning.

**Comment by jenhicks** [comment]
@AlbertoCasasOrtiz Can you fix the special characters? Is it also linked from somehwere within the app?

**Comment by AlbertoCasasOrtiz** [comment]
Hi @jenhicks, Nick and I found the[ script to update the static site](https://github.com/keenon/AddBiomechanics/blob/main/deploy_static.sh) and tried to upload the fix for the special characters, but looks like we do not have permissions to do it.

Regarding linking to it from the app, you will be able to access from the menu when you click on your user's profile, but I just noticed it is not possible to access if you are not logged in (so users without an account who are just exploring the datasets cannot access to it), so I will look for a better/additional place for it.

We'll ask Keenon to give us permissions and to update the static site once he is back next week.
